# =============================================================================
# Ansible Inventory - Auto-generated from Terraform
# =============================================================================
# DO NOT EDIT MANUALLY - This file is generated by Terraform
# =============================================================================

all:
  vars:
    ansible_user: ${ssh_user}
    ansible_ssh_private_key_file: ~/.ssh/orange-wallet-key
    ansible_python_interpreter: /usr/bin/python3

    # K3s configuration
    k3s_version: v1.28.5+k3s1
    project_name: orange-wallet
    environment: dev
    timezone: Asia/Jakarta

  children:
    k3s_master:
      hosts:
        ${master_name}:
          ansible_host: ${master_ip}
          node_role: master
          workload_type: control-plane

    k3s_workers_stateless:
      hosts:
%{ for worker in stateless_workers ~}
        ${worker.name}:
          ansible_host: ${worker.ip}
          node_role: worker
          workload_type: stateless
%{ endfor ~}

    k3s_workers_stateful:
      hosts:
%{ for worker in stateful_workers ~}
        ${worker.name}:
          ansible_host: ${worker.ip}
          node_role: worker
          workload_type: stateful
          node_taint: "stateful=true:NoSchedule"
%{ endfor ~}

    k3s_workers:
      children:
        k3s_workers_stateless:
        k3s_workers_stateful:

    k3s_cluster:
      children:
        k3s_master:
        k3s_workers:
